contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mitoforge channel"
    url: https://nfcore.slack.com/channels/mitoforge
    about: Discussion about the rcac-bioinformatics/mitoforge pipeline
